name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Cache docker
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache-server
        key: ${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ${{ github.ref }}
          refs/head/main
    
    - name: Build server image
      uses: docker/build-push-action@v5
      with:
        push: false
        builder: ${{ steps.buildx.outputs.name }}
        tags: app-server
        load: true
        context: .
        file: ./app-server/Dockerfile
        cache-from: type=local,src=/tmp/.buildx-cache-server
        cache-to: type=local,dest=/tmp/.buildx-cache-new-server

    - name: Build with Docker Compose
      run: |
        docker compose build

    - name: Update cache
      run: |
        rm -rf /tmp/.buildx-cache-server
        mv /tmp/.buildx-cache-new-server /tmp/.buildx-cache-server
